In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder

In [4]:
df=pd.read_csv('../data/data2022.csv')
print(df.columns)

Index(['State', 'Sex', 'GeneralHealth', 'PhysicalHealthDays',
       'MentalHealthDays', 'LastCheckupTime', 'PhysicalActivities',
       'SleepHours', 'RemovedTeeth', 'HadHeartAttack', 'HadAngina',
       'HadStroke', 'HadAsthma', 'HadSkinCancer', 'HadCOPD',
       'HadDepressiveDisorder', 'HadKidneyDisease', 'HadArthritis',
       'HadDiabetes', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'SmokerStatus',
       'ECigaretteUsage', 'ChestScan', 'RaceEthnicityCategory', 'AgeCategory',
       'HeightInMeters', 'WeightInKilograms', 'BMI', 'AlcoholDrinkers',
       'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap',
       'HighRiskLastYear', 'CovidPos'],
      dtype='object')


In [5]:
df=pd.read_csv('../data/data2022.csv')
df.head()
'''
columns_to_keep = [
    'HeartDisease','BMI', 'Smoking', 'Stroke', 'PhysicalHealthDays',
    'DiffWalking', 'Sex', 'AgeCategory', 'Diabetic',
    'Asthma', 'KidneyDisease'
]

df = df[columns_to_keep]
'''

"\ncolumns_to_keep = [\n    'HeartDisease','BMI', 'Smoking', 'Stroke', 'PhysicalHealthDays',\n    'DiffWalking', 'Sex', 'AgeCategory', 'Diabetic',\n    'Asthma', 'KidneyDisease'\n]\n\ndf = df[columns_to_keep]\n"

In [6]:
df1 = df.copy()
le=LabelEncoder()
categorical = df.select_dtypes(include = 'O')
categorical.columns
for feature in categorical:
    df1[feature]=le.fit_transform(df1[feature])
    print(feature)

State
Sex
GeneralHealth
LastCheckupTime
PhysicalActivities
RemovedTeeth
HadHeartAttack
HadAngina
HadStroke
HadAsthma
HadSkinCancer
HadCOPD
HadDepressiveDisorder
HadKidneyDisease
HadArthritis
HadDiabetes
DeafOrHardOfHearing
BlindOrVisionDifficulty
DifficultyConcentrating
DifficultyWalking
DifficultyDressingBathing
DifficultyErrands
SmokerStatus
ECigaretteUsage
ChestScan
RaceEthnicityCategory
AgeCategory
AlcoholDrinkers
HIVTesting
FluVaxLast12
PneumoVaxEver
TetanusLast10Tdap
HighRiskLastYear
CovidPos


In [10]:
def split_data(X, Y, feature):
    # X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2,stratify=Y)
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2,stratify=df1[feature])
    return X_train, X_test, y_train, y_test
def over_sample_date(X_train, y_train, data_rate = 1):
    minority_class = y_train.value_counts().idxmin()    # 1
    majority_class = y_train.value_counts().idxmax()    # 0

    minority_data = X_train[y_train == minority_class]
    majority_data = X_train[y_train == majority_class]
    minority_labels = y_train[y_train == minority_class]
    majority_labels = y_train[y_train == majority_class]

    oversampled_minority_data = minority_data.sample(int(len(majority_data)*data_rate), replace=True)
    oversampled_minority_labels = minority_labels.sample(int(len(majority_data)*data_rate), replace=True)
    X_train_oversampled = pd.concat([majority_data, oversampled_minority_data])
    y_train_oversampled = pd.concat([majority_labels, oversampled_minority_labels])
    return X_train_oversampled, y_train_oversampled

## Change data_rate and other things to improve the data

In [43]:
# get the training dataset and test dataset
X=df1.drop('HadHeartAttack',axis=1)
Y=df1['HadHeartAttack']
X_train, X_test, y_train, y_test = split_data(X,Y, "HadHeartAttack")
X_train_oversampled, Y_train_oversampled = over_sample_date(X_train, y_train, data_rate = 1)

In [44]:
# transform the training data
scaler = StandardScaler()
X_train_oversampled_T = scaler.fit_transform(X_train_oversampled)
X_test_T = scaler.transform(X_test)

In [45]:
log_reg = LogisticRegression()
log_reg.fit(X_train_oversampled_T, Y_train_oversampled)

y_pred = log_reg.predict(X_test_T)
#acc=log_reg.score(y_test,y_pred)
print(classification_report(y_test, y_pred))
confusion_matrix(y_test,y_pred)

              precision    recall  f1-score   support

           0       0.98      0.83      0.90     46518
           1       0.21      0.77      0.33      2687

    accuracy                           0.83     49205
   macro avg       0.60      0.80      0.62     49205
weighted avg       0.94      0.83      0.87     49205


array([[38747,  7771],
       [  623,  2064]])

In [46]:
log_reg.coef_,log_reg.intercept_

(array([[-0.00136227,  0.37913133, -0.03444018,  0.0871154 ,  0.03910174,
          0.11544806, -0.04395245, -0.05543116, -0.06759481,  1.17076279,
          0.33339695,  0.03266067, -0.02204017,  0.06829962,  0.02989891,
          0.06831557,  0.0286537 ,  0.18987811,  0.05294126,  0.06515129,
          0.04416603,  0.09895978, -0.03410858,  0.0588833 , -0.21117684,
          0.03572442,  0.34976337, -0.00572757,  0.69643557, -0.1476619 ,
          0.17557901, -0.11312748, -0.13325854, -0.00568753, -0.0787146 ,
          0.02571391, -0.01498358,  0.02436731,  0.02283218]]),
 array([0.16600727]))

In [47]:
from sklearn.preprocessing import StandardScaler
import pickle
def normalize_row(row, scaler):
    # Reshape row to match expected input of scaler
    row_reshaped = row.values.reshape(1, -1)
    # Apply the same transformation as training data
    normalized_row = scaler.transform(row_reshaped)
    return normalized_row  # Flatten to match the shape of the original row

# Fit scaler
scaler = StandardScaler().fit(X_train_oversampled.values)
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
df_new = X_train_oversampled.iloc[0]

df_new_normalized = normalize_row(df_new, scaler)

print(df_new_normalized)

# If true, this proof the correctness of normalization
print(X_train_oversampled_T[0] == df_new_normalized)


[[ 1.00448853 -1.10945754 -0.16499011 -0.51520952 -0.18001931  0.37420921
   0.64011494 -0.63060109 -0.48286087  1.65271139 -0.35163785  2.24666072
   2.83439435  2.42463054 -0.53795208 -0.31438525  1.10011476  1.70584444
  -0.40179989 -0.2973369  -0.39932005 -0.59019985 -0.2589463   2.83053256
   0.77702643 -0.46208217  0.84454938 -0.29817373  0.3453844  -0.27890557
   1.10014192  1.48333217 -0.95344425  1.43081769  0.85504849  0.95737533
  -0.14575936 -0.18983213  1.61139995]]
[[ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True]]


In [16]:
print(list(X_train_oversampled.iloc[0]))

[26.63, 1.0, 0.0, 0.0, 0.0, 1.0, 10.0, 0.0, 0.0, 0.0]


In [19]:
# Use user input to get 
import numpy as np

user_input = [29.76, 0.0, 0.0, 0.0, 0.0, 1.0, 7.0, 0.0, 0.0, 0.0]
with open('scaler.pkl', 'rb') as f:
    scaler2 = pickle.load(f)
user_input_T = normalize_row(pd.DataFrame([user_input]),scaler2)

coef = np.array([0.09889642, 0.22637016, 0.30912101, 0.2488255 , 0.18334112,
         0.37937364, 1.03940385, 0.25440507, 0.13933909, 0.17579232]).flatten()
intercept = -1.29850855

# Compute the linear combination of inputs and weights
z = np.dot(user_input_T, coef) + intercept

# Apply the logistic function
p = 1 / (1 + np.exp(-z))

print("The predicted probability is:", p)


The predicted probability is: [0.16067047]


In [21]:
col = (list(df.columns[1:]))
coef = (list(log_reg.coef_[0]))
print(len(col), len(coef))
num = 0;
for i in range(len(col)):
    if(coef[i] > 0.08 or coef[i] < -0.08):
        print(col[i], coef[i])
        num+=1
print(num)

39 39
GeneralHealth 0.36402090284437594
PhysicalActivities 0.10137818621197459
HadAngina 0.9737636569231289
HadStroke 0.27964870799377695
HadDiabetes 0.17573292365639212
DifficultyWalking 0.08256261882192018
SmokerStatus -0.19966559729113295
ChestScan 0.3410593024476512
AgeCategory 0.6594176125386868
AlcoholDrinkers -0.12724874632043026
FluVaxLast12 -0.08333360627771243
11


In [49]:
columns = list(df.columns[1:])
coefficients = list(log_reg.coef_[0])

features_with_coef = list(zip(columns, coefficients))

sorted_features = sorted(features_with_coef, key=lambda x: abs(x[1]), reverse=True)

top_features = sorted_features[:10]

for feature, coef in top_features:
    print(feature)
print(len(top_features))


HadAngina
AgeCategory
GeneralHealth
ChestScan
HadStroke
SmokerStatus
HadDiabetes
WeightInKilograms
HeightInMeters
AlcoholDrinkers
10


In [ ]:
feature_list = [
    "HadAngina",
    "AgeCategory",
    "GeneralHealth",
    "ChestScan",
    "HadStroke",
    "SmokerStatus",
    "HadDiabetes",
    "WeightInKilograms",
    "HeightInMeters",
    "AlcoholDrinkers"
]

In [123]:
import pickle
from joblib import dump, load
df=pd.read_csv('../data/data2022.csv')
df.head()

feature_list = [
    "HadHeartAttack",
    "HadAngina",
    "AgeCategory",
    "GeneralHealth",
    "ChestScan",
    "HadStroke",
    "SmokerStatus",
    "HadDiabetes",
    "WeightInKilograms",
    "HeightInMeters",
    "AlcoholDrinkers"
]

df = df[feature_list]
df1 = df.copy()
le=LabelEncoder()
categorical = df.select_dtypes(include = 'O')
categorical.columns
for feature in categorical:
    df1[feature]=le.fit_transform(df1[feature])

X=df1.drop('HadHeartAttack',axis=1)
Y=df1['HadHeartAttack']
X_train, X_test, y_train, y_test = split_data(X,Y, "HadHeartAttack")
X_train_oversampled, Y_train_oversampled = over_sample_date(X_train, y_train, data_rate = 1)
scaler = StandardScaler()
X_train_oversampled_T = scaler.fit_transform(X_train_oversampled)
X_test_T = scaler.transform(X_test)

log_reg = LogisticRegression()
log_reg.fit(X_train_oversampled_T, Y_train_oversampled)

y_pred = log_reg.predict(X_test_T)

print(classification_report(y_test, y_pred))
confusion_matrix(y_test,y_pred)

print(log_reg.coef_,log_reg.intercept_)

scaler = StandardScaler().fit(X_train_oversampled.values)
with open('./saved_files/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

dump(log_reg, './saved_files/logistic_model.joblib')


              precision    recall  f1-score   support

           0       0.98      0.83      0.90     46518
           1       0.20      0.76      0.32      2687

    accuracy                           0.83     49205
   macro avg       0.59      0.80      0.61     49205
weighted avg       0.94      0.83      0.87     49205

[[ 1.20418188  0.71994361 -0.07368749  0.4308176   0.38058965 -0.29344281
   0.23605199  0.13270312  0.09138451 -0.16525378]] [0.15924511]


['./saved_files/logistic_model.joblib']

In [124]:
# Load the model back from the file

loaded_model = load('./saved_files/logistic_model.joblib')

# Use loaded_model to predict or evaluate to ensure it works
predictions = loaded_model.predict_proba(X_test_T[20:31])
print(predictions[:])

[[0.68924272 0.31075728]
 [0.50556966 0.49443034]
 [0.51268851 0.48731149]
 [0.62306698 0.37693302]
 [0.87725271 0.12274729]
 [0.67972368 0.32027632]
 [0.87716042 0.12283958]
 [0.74783605 0.25216395]
 [0.9073931  0.0926069 ]
 [0.9385693  0.0614307 ]
 [0.79489329 0.20510671]]
